<?php
// @codingStandardsIgnoreFile

/** @var $block \Dmatthew\AttributeDescription\Block\Adminhtml\Attribute\Edit\Options\Descriptions  */
?>

<div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="manage-descriptions-wrapper">
    <div class="fieldset-wrapper-description">
        <strong class="admin__collapsible-description" data-toggle="collapse" data-target="#manage-descriptions-content">
            <span><?php /* @escapeNotVerified */ echo __('Manage Attribute Descriptions') ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="manage-descriptions-content">
        <fieldset class="fieldset">
            <div>
                <?php $_descriptions = $block->getDescriptionValues() ?>
                <?php foreach ($block->getStores() as $_store): ?>
                    <div class="field admin__field">
                        <label class="admin__field-label label">
                            <?php /* @escapeNotVerified */ echo $_store->getName() ?>
                        </label>
                        <div class="control admin__field-control">
                            <textarea class="admin__control-textarea<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>"
                                      name="frontend_description[<?php /* @escapeNotVerified */ echo $_store->getId() ?>]"
                                      rows="5"
                                      cols="25"
                                      <?php if ($block->getReadOnly()):?> disabled="disabled"<?php endif;?>><?php echo $block->escapeHtml($_descriptions[$_store->getId()]) ?></textarea>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
    </div>
</div>
