<?php
// @codingStandardsIgnoreFile

/** @var $block \Dmatthew\AttributeDescription\Block\Adminhtml\Attribute\Edit\Options\Descriptions  */
?>
<div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="manage-descriptions-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="admin__collapsible-title" data-toggle="collapse" data-target="#manage-descriptions-content">
            <span><?= /* @escapeNotVerified */ __('Manage Attribute Descriptions') ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="manage-descriptions-content">
        <fieldset class="admin__fieldset fieldset">
            <div class="admin__control-table-wrapper">
                <table class="admin__control-table" id="attribute-descriptions-table">
                    <thead>
                    <tr>
                        <?php foreach ($block->getStores() as $_store): ?>
                            <th class="col-store-view"><?= /* @escapeNotVerified */ $_store->getName() ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
	                    <?php $_descriptions = $block->getDescriptionValues() ?>
                        <?php foreach ($block->getStores() as $_store): ?>
                            <td class="col-store-view">
	                            <div class="control">
									<textarea class="admin__control-textarea textarea<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>"
										name="frontend_description[<?= /* @escapeNotVerified */ $_store->getId() ?>]"
										rows="5"
										cols="25"
										<?php if ($block->getReadOnly()):?> disabled="disabled"<?php endif;?>><?= $block->escapeHtml($_descriptions[$_store->getId()]) ?></textarea>
	                            </div>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>
